name: Setup workspace

inputs:
  os:
    description: Runner OS used for workspace setup
    required: true
  node-version:
    description: Node.js version to install
    required: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

runs:
  using: composite
  steps:
    - name: Setup Node version ⚙️
      uses: ./.github/actions/setup-node
      with:
        cache-dependency-path: 'package-lock.json'
        node-version: ${{ inputs.node-version }}

    - name: Install 🔧
      run: npm ci --ignore-scripts --prefer-offline
      shell: bash
