@startuml "Jest require()"

start

:require('file');

if (has a transform?) then (yes)
  if (transformer has getCacheKey?) then (yes)
    :transformer.getCacheKey(...);
  else (no)
    :use jest built-in;
  endif

  if (in cache?) then (yes)
    :use cache content;
  else (no)
    :transformer.process(...);
    :update cache;
  endif

else (no)
endif

:require();

end

@enduml
