@startuml "Preparing E2E tests"
start

:bundle ts-jest;
note right
  will build ts-jest before creating the bundle
end note

:create temp work dir;
note right
  `e2e/~__workdir_symlink__` links to it
  except on CI environments
end note

while (for each template)
  note right
    tempaltes are in `e2e/~__templates__/`
  end note

  if (template's build directory) then (esists)
    :wipe but `node_modules` dir;
  else (not exists)
    :create;
  endif

  :copy files from template's dir to its build dir;

  if (package lock file) then (exists)
    :read metadata;

    if (package lock file) then (has changed)
      :remove `node_modules` dir;

      :npm install (or ci);

      :npm install ts-jest bundle;

    else if (ts-jest bundle) then (has changed)
      :npm install ts-jest bundle;

    else (hasn't changed)
    endif
    :write updated metadata;

  else (not exists)
  endif

endwhile (done)

:all templates ready;

stop

@enduml
