name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare-npm-cache-ubuntu:
    uses: ./.github/workflows/prepare-cache.yml
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    with:
      os: ubuntu-latest
      node-version: ${{ matrix.node-version }}

  prepare-npm-cache-windows:
    uses: ./.github/workflows/prepare-cache.yml
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    with:
      os: windows-latest
      node-version: ${{ matrix.node-version }}

  test-ubuntu:
    permissions:
      checks: write
      contents: read
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-ubuntu
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    with:
      os: ubuntu-latest
      node-version: ${{ matrix.node-version }}

  test-windows:
    permissions:
      checks: write
      contents: read
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-windows
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    with:
      os: windows-latest
      node-version: ${{ matrix.node-version }}

  lint:
    runs-on: ubuntu-latest
    needs: prepare-npm-cache-ubuntu

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup workspace ⚙️
        uses: ./.github/actions/setup-workspace
        with:
          os: ubuntu-latest
          node-version: 20.x

      - name: Run lint 🔍
        run: npm run lint

      - name: Run prettier 💅
        run: npm run lint-prettier-ci

  sonar-scan:
    permissions:
      checks: write
      contents: read
    needs: [test-ubuntu, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup workspace ⚙️
        uses: ./.github/actions/setup-workspace
        with:
          os: ubuntu-latest
          node-version: 20

      - name: Build 🔧
        run: npm run build

      - name: Run tests with coverage 🧪
        run: npm run test -- --coverage
        env:
          CI: true
          DISABLE_MOCKED_WARNING: true

      - name: SonarCloud Scan 📊
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  finish:
    permissions:
      checks: write
    needs: [test-ubuntu, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Coveralls 📊
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
        env:
          CI: true
